name: golangci-lint
on:
  pull_request:
  push:
    branches:
      - main*

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      # Config options can be found in README here: https://github.com/golangci/golangci-lint-action
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: ./.github/actions/setup-go
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.12.2
