name: govulncheck
on:
  pull_request:
  push:
    branches:
      - main*

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: ./.github/actions/setup-go
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck -show=traces -test ./...
